version: "3.9"

services:
  postgres:
    image: "postgres:15.2-alpine"
    ports:
      - "5432:5432"
    env_file:
      - ./.env.db
  pg_proxy:
    image: ghcr.io/neondatabase/wsproxy:latest
    environment:
      APPEND_PORT: "postgres:5432"
      ALLOW_ADDR_REGEX: ".*"
      LOG_TRAFFIC: "true"
    ports:
      - "5433:80"
    depends_on:
      - postgres
